config/routes.rb
Rails.application.routes.draw do
root to: 'homes#index'
 # get 'books/index'
 # get 'books/show'
 #  get 'books/new'
 #  get 'books/edit'
 #  get 'bookers/index'
 #  get 'bookers/show'
 #  get 'bookers/new'
 #  get 'bookers/edit'
 #  get 'blogs/index'
 #  get 'blogs/show'
 #  get 'blogs/new'
 #  get 'blogs/edit' デフォルトであったルートを念のため残しておく ただしhomsは削除
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
resources :books

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

 validates :title, presence: true
 validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
protect_from_forgery with: :null_session
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books= Book.all
    @book = Book.new
  end

  def show
    @books = Book.find(params[:id])
  end

  def create
    @book = Book.new(books_params)
    if @book.save
      flash[:success] = "Book was successfully created."
      redirect_to book_path(@book)

    else
      @books = Book.all

      flash[:danger] = "createerrer"
      render :index

    end

  end

  def edit
    @book = Book.find(params[:id])
  end

  def update

    @book = Book.find(params[:id])
  

    if @book.update(books_params)
      flash[:success] = "updatesuccessfully"
      redirect_to book_path

    else
      flash[:danger] = "updat.eerrer"
      render :edit

    end
  end


   def destroy
    book = Book.find(params[:id])

    if book.destroy
      flash[:success] = "destroy.successfully"
      redirect_to books_path

    end

   end

  private
  def books_params
    params.require(:book).permit(:title, :body)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end

  def show
    @top = resources :homes
  end

  def new
    
  end

  def edit
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/todolists_helper.rb
module TodolistsHelper
end

app/views/books/edit.html.erb
<%= flash[:success] %>

<% if @book.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %> 'error' </li>
      <% end %>
    </ul>
  </div>
<% end %>


<h1>Editing Book</h1>

<%= form_with model:@book, local: true do |f| %>
  <label for="book_title">Title</label>
  <%= f.text_field :title %>


  <label for="book_body">Body</label>
  <%= f.text_area :body %>



<div class="actions">

  <%= f.submit 'Update Book' %>
</div>



<% end %>


<%=link_to 'Show', book_path(@book) %>

<span>|</span>


<%=link_to 'Back', books_path %>

app/views/books/index.html.erb
<%= flash[:success] %>

<% if @book.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %> 'error' </li>
        
      <% end %>
    </ul>
  </div>
<% end %>







<h1>Books</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>

     <% @books.each do |list| %>
    <tr>
    <td><%= list.title %></td>

    <td><%= list.body %></td>

     <td><%= link_to "Show", book_path(list.id)%></td>
     <td><%= link_to "Edit", edit_book_path(list.id)%></td>
     <td><%= link_to "Destroy", book_path(list.id), method: :delete %></td>

    </tr>
    <% end %>
  </table>


  
<%= form_with model: @book, local:true do |f| %>

  <h2>New book</h2>
  <h5>Title</h5>
  <%= f.text_field :title %>
 

  <h5>body</h5>
  <%= f.text_area :body %>
 

  <%= f.submit 'Create Book' %>

<% end %>

app/views/books/show.html.erb
<%= flash[:success] %>



<p><strong>Title: </strong><%= @books.title %><p>
<p><strong>Body: </strong><%= @books.body %></p>



<%=link_to 'Edit', edit_book_path(@books) %>

<span>|</span>


<%=link_to 'Back', books_path %>

app/views/homes/edit.html.erb
<h1>ようこそ Bookers へ！</h1>
<% @top.each do |books| %>
<!DOCTYPE html>
<html>
  <head>
    <title>WebCampBackendNew</title>
    <meta name="csrf-param" content="authenticity_token" />
<meta name="csrf-token" content="qQUMdpI1o5GgH+6cgRjg+qEZfR/ibuLHqRLqu4Vj2EGu18Grz24W+kDdog/M6u742lxR0suT8coYUwpWJcvZ3A==" />

    <link rel="stylesheet" media="all" href="/assets/application-d12397cbc3a266ce5a99f7b588223090c55ca04a439953bb5f9304395de93fc3.css" data-turbolinks-track="reload" />
    <script src="/assets/application-114264dd93c8ff30e4335b71eed7949d66c4e7a8eb62e2de6284c046fe07104b.js" data-turbolinks-track="reload"></script>
  </head>

  <body>
    <h1>ようこそ <strong>Bookers</strong>  へ！</h1>
<p><strong>Bookers</strong>  では、さまざまな書籍に関するあなたの意見や</p><p>印象を共有し交換することができます</p>
<p><a href="/books">start</a></p>    	
  </body>
</html>

app/views/homes/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WebCampBackendNew</title>
    <meta name="csrf-param" content="authenticity_token" />
<meta name="csrf-token" content="qQUMdpI1o5GgH+6cgRjg+qEZfR/ibuLHqRLqu4Vj2EGu18Grz24W+kDdog/M6u742lxR0suT8coYUwpWJcvZ3A==" />

    <link rel="stylesheet" media="all" href="/assets/application-d12397cbc3a266ce5a99f7b588223090c55ca04a439953bb5f9304395de93fc3.css" data-turbolinks-track="reload" />
    <script src="/assets/application-114264dd93c8ff30e4335b71eed7949d66c4e7a8eb62e2de6284c046fe07104b.js" data-turbolinks-track="reload"></script>
  </head>

  <body>
    <h1>ようこそ <strong>Bookers</strong>  へ！</h1>
<p><strong>Bookers</strong>  では、さまざまな書籍に関するあなたの意見や</p><p>印象を共有し交換することができます</p>
<p><a href="/books">start</a></p>    	
  </body>
</html>

app/views/homes/new.html.erb
<!DOCTYPE html!>
<html>
<head>
  <link rel="stylesheet" media="all" href="/assets/application-d12397c….css" data-turbolinks-track="reload">
  <script src="/assets/application-114264d….js" data-turbolinks-track="reload"></script>
  <title>WebCampBackendNew</title>
  <meta name="csrf-param" content="authenticity_token">
  <meta name="csrf-token" content="NNSp7K54Ywb+Omxy5ZPJ8NeVugfi6BXqXdkBo20l5AmxFfohyLrEhSNzkleaLXsZuAPkfHcJSP9bldClNmW+gw==">
  <link rel="stylesheet" media="all" href="/assets/application-d12397c….css" data-turbolinks-track="reload">
  <script src="/assets/application-114264d….js" data-turbolinks-track="reload"></script>
</head>

<body>

  <p id="notice"></p>
  <h1>Books</h1>
   <teble>
     <thead>
       <tr>
         <th>Title</th>
         <th>Body</th>
           <th colspan="3"></th>
        </tr>
     </thead>
   </table>
  <h2>New book</h2>
  <form class="new_book" id="new_book" action="/books" accept-charset="UTF-8" method="post">
    <input name="utf8" type="hidden" value="✓">
    <input type="hidden" name="authenticity_token" value="NNSp7K54Ywb+Omxy5ZPJ8NeVugfi6BXqXdkBo20l5AmxFfohyLrEhSNzkleaLXsZuAPkfHcJSP9bldClNmW+gw==">
    <div class="field">
      <label for="book_title">Title</label>
      <input class="book_title" type="text" name="book[title]" id="book_title">
    </div>
    <div class="field">
      <label for="book_body">Body</label>
      <textarea class="book_body" name="book[body]" id="book_body"></textarea>
    </div>
    <div class="actions">
      <input type="submit" name="commit" value="Create Book" data-disable-with="Create Book">
    </div>
  </form>
  </body>
</html>

app/views/homes/show.html.erb
<h1>Homes#show</h1>
<p>Find me in app/views/homes/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>